stages:
        - deploy

deploy-to-production-server:
        stage: deploy
        only:
                -master
        script:
                -./mvnw clean package
                -cd target
                -java -jar *.jar
